USE EMAILCLIENT;
DROP TABLE IF EXISTS EmailToAddress;

CREATE TABLE EMAILTOADDRESS (
  EMAILTOADDRESSKEY int(11) NOT NULL auto_increment,
  EMAILID int(11) NOT NULL,
  ADDRESSID int(11) NOT NULL,
  RECIPIENTCATEGORY varchar(3) NOT NULL default 'TO',
  CONSTRAINT fkemailid FOREIGN KEY (EMAILID) REFERENCES EMAIL(EMAILID),
  CONSTRAINT fkaddressid FOREIGN KEY (ADDRESSID) REFERENCES ADDRESSES(ADDRESSID),
  PRIMARY KEY  (EMAILTOADDRESSKEY)
);

INSERT INTO EMAILTOADDRESS (EMAILID,ADDRESSID,RECIPIENTCATEGORY) values (1,2,'TO'),(1,3,'CC'),(1,4,'BCC');

INSERT INTO EMAILTOADDRESS (EMAILID,ADDRESSID,RECIPIENTCATEGORY) values (2,1,'TO'),(2,3,'CC'),(2,4,'CC');

INSERT INTO EMAILTOADDRESS (EMAILID,ADDRESSID,RECIPIENTCATEGORY) values (3,1,'BCC'),(3,2,'BCC');

INSERT INTO EMAILTOADDRESS (EMAILID,ADDRESSID,RECIPIENTCATEGORY) values (4,4,'TO');
